### ISSUE TITLE
Weird highlighting on Results #h2

### ISSUE THREAD

**Issue by sihugh** [alphagov/calculators#132]
When you complete the child benefit tax calculator, you end up at a URL like [this one](https://www.gov.uk/child-benefit-tax-calculator/main?childcare=&children_count=1&cycle_scheme=&gift_aid_donations=&gross_income=%C2%A345%2C666.00&non_employment_income=&other_income=&outgoing_pension_contributions=&pension_contributions_from_pay=&pensions=&property=&results=Calculate&retirement_annuities=&starting_children%5B0%5D%5Bstart%5D%5Bday%5D=7&starting_children%5B0%5D%5Bstart%5D%5Bmonth%5D=1&starting_children%5B0%5D%5Bstart%5D%5Byear%5D=2002&starting_children%5B0%5D%5Bstop%5D%5Bday%5D=&starting_children%5B0%5D%5Bstop%5D%5Bmonth%5D=&starting_children%5B0%5D%5Bstop%5D%5Byear%5D=&year=2015#results)

There is weird highlighting around the `Results` tag, which disappears when it goes out of focus.  (ie click on another part of the page) 

![screen shot 2016-03-16 at 12 56 49](https://cloud.githubusercontent.com/assets/773037/13813415/5bd1e352-eb79-11e5-9aeb-772664d646eb.png)

**Comment by floehopper** [comment]
@erikse, @ikennaokpala, @pmanrubia, @chrisroos: Do you know which team is currently responsible for this app? If it's us, then I'd suggest turning this into a Trello card on the [Content Development board](https://trello.com/b/bVfnXnEc/content-development). If not then we should make sure the relevant team (Custom Formats?) is aware of it. /cc @jennyd

**Comment by sihugh** [comment]
Yep, it's custom. I will write a card when I'm back in, but just wanted to
keep a track of it.

**Comment by floehopper** [comment]
Thanks :+1:

**Comment by sihugh** [comment]
Fixed by https://github.com/alphagov/calculators/pull/171
