### ISSUE TITLE
Long URL error not logged to Erbit

### ISSUE THREAD

**Issue by andysellick** [alphagov/calculators#186]
The calculator currently passes all input values as GET, meaning that it's possible to create very long URLs by typing long values into the form (for normal use this shouldn't be a problem for modern browsers, although attempting to claim for part of the year for 10 children can result in a URL of length > 3000 chars, limit for older IE is 2000).

If you trigger this, for example by putting in a ridiculously long number into each of the number fields, it triggers a 500 error, but it doesn't appear that this is being logged correctly in Erbit.

**Comment by tijmenb** [comment]
This is a user-error and shouldn't be reported to errbit (now Sentry) according to https://docs.publishing.service.gov.uk/manual/errors.html
