### ISSUE TITLE
Update form styles to use form components

### ISSUE THREAD

**Issue by fofr** [alphagov/calculators#243]
Calculators uses the latest form styles from Elements. It should instead use the styles that government-frontend and now email-alert-frontend use, by reusing the form components in govuk_publishing_components.

eg
https://government-frontend.herokuapp.com/component-guide/radio
https://government-frontend.herokuapp.com/component-guide/error_summary

**Comment by tijmenb** [comment]
Totally agree. Now tracked here: https://trello.com/c/kQMyItaS
